//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFW2C.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceExceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceExceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFW2C.Resources.ResourceExceptions", typeof(ResourceExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already added in.
        /// </summary>
        internal static string Already_Added_In {
            get {
                return ResourceManager.GetString("Already_Added_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is already added to .
        /// </summary>
        internal static string Already_Added_To {
            get {
                return ResourceManager.GetString("Already_Added_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one employer record should be provided..
        /// </summary>
        internal static string AtLeast_OneEmployer_Record_ShouldBe_Provided {
            get {
                return ResourceManager.GetString("AtLeast_OneEmployer_Record_ShouldBe_Provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t be blank..
        /// </summary>
        internal static string Cant_Be_Blank {
            get {
                return ResourceManager.GetString("Cant_Be_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t be blank if .
        /// </summary>
        internal static string Cant_Be_Blank_If {
            get {
                return ResourceManager.GetString("Cant_Be_Blank_If", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t be empty.
        /// </summary>
        internal static string Cant_Be_Empty {
            get {
                return ResourceManager.GetString("Cant_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country code is not correct..
        /// </summary>
        internal static string CountryCode_IsNot_Correct {
            get {
                return ResourceManager.GetString("CountryCode_IsNot_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create manager faild..
        /// </summary>
        internal static string Create_Manager_Faild {
            get {
                return ResourceManager.GetString("Create_Manager_Faild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is closed..
        /// </summary>
        internal static string Document_Is_Closed {
            get {
                return ResourceManager.GetString("Document_Is_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is opened.
        /// </summary>
        internal static string Document_Is_Opened {
            get {
                return ResourceManager.GetString("Document_Is_Opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t  belong to .
        /// </summary>
        internal static string Doesnt_BelongTo {
            get {
                return ResourceManager.GetString("Doesnt_BelongTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is empty.
        /// </summary>
        internal static string Email_Is_Empty {
            get {
                return ResourceManager.GetString("Email_Is_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not correct.
        /// </summary>
        internal static string Email_Is_Not_Correct {
            get {
                return ResourceManager.GetString("Email_Is_Not_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception is not defined.
        /// </summary>
        internal static string Exception_Not_Defined {
            get {
                return ResourceManager.GetString("Exception-Not-Defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field  is required..
        /// </summary>
        internal static string Field_Is_Required {
            get {
                return ResourceManager.GetString("Field_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must be.
        /// </summary>
        internal static string Field_MustBe {
            get {
                return ResourceManager.GetString("Field_MustBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not correct..
        /// </summary>
        internal static string File_IsNot_Correct {
            get {
                return ResourceManager.GetString("File_IsNot_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not exists..
        /// </summary>
        internal static string File_IsNot_Exists {
            get {
                return ResourceManager.GetString("File_IsNot_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaild only for year 1987 to 2005..
        /// </summary>
        internal static string For_Year_87_And_05 {
            get {
                return ResourceManager.GetString("For_Year_87_And_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has no field or not added tp blankList..
        /// </summary>
        internal static string HasNo_Field_OrNot_AddedTo_BlankList {
            get {
                return ResourceManager.GetString("HasNo_Field_OrNot_AddedTo_BlankList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if year 2023, value must not exceed .
        /// </summary>
        internal static string If_Year2023_Value_Must_NotExceed {
            get {
                return ResourceManager.GetString("If_Year2023_Value_Must_NotExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error:- .
        /// </summary>
        internal static string Internal_Error {
            get {
                return ResourceManager.GetString("Internal_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invaild file..
        /// </summary>
        internal static string Invaild_File {
            get {
                return ResourceManager.GetString("Invaild_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid class.
        /// </summary>
        internal static string Invalid_Class {
            get {
                return ResourceManager.GetString("Invalid_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not valid vagent indicator..
        /// </summary>
        internal static string Is_Not_Valid_Agent_Indicator {
            get {
                return ResourceManager.GetString("Is_Not_Valid_Agent_Indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not valid Employment Code..
        /// </summary>
        internal static string Is_Not_Valid_Employment_Code {
            get {
                return ResourceManager.GetString("Is_Not_Valid_Employment_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is empty..
        /// </summary>
        internal static string IsEmpty {
            get {
                return ResourceManager.GetString("IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not defined.
        /// </summary>
        internal static string IsNot_Defined {
            get {
                return ResourceManager.GetString("IsNot_Defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not provided..
        /// </summary>
        internal static string IsNot_Provided {
            get {
                return ResourceManager.GetString("IsNot_Provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not vaild KindOfEmployer..
        /// </summary>
        internal static string IsNot_Vaild_KindOfEmployer {
            get {
                return ResourceManager.GetString("IsNot_Vaild_KindOfEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not valid resub wage file..
        /// </summary>
        internal static string IsNot_Valid_Resub_Wage_File {
            get {
                return ResourceManager.GetString("IsNot_Valid_Resub_Wage_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenght must be exactly .
        /// </summary>
        internal static string Lenght_MustBe_Exactly {
            get {
                return ResourceManager.GetString("Lenght_MustBe_Exactly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length exceeds .
        /// </summary>
        internal static string Length_Exceeds {
            get {
                return ResourceManager.GetString("Length_Exceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length is not set..
        /// </summary>
        internal static string Length_Is_Not_Set {
            get {
                return ResourceManager.GetString("Length_Is_Not_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Original reported money filed must not be the same as the correct money field..
        /// </summary>
        internal static string Money_Original_Must_Not_SameAs_Correct {
            get {
                return ResourceManager.GetString("Money_Original_Must_Not_SameAs_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be added to .
        /// </summary>
        internal static string Must_Be_AddedTo {
            get {
                return ResourceManager.GetString("Must_Be_AddedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be blank.
        /// </summary>
        internal static string Must_Be_Blank {
            get {
                return ResourceManager.GetString("Must_Be_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be blank if employment code is .
        /// </summary>
        internal static string Must_Be_Blank_If_EmploymentCode_Is {
            get {
                return ResourceManager.GetString("Must_Be_Blank_If_EmploymentCode_Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be blank. Otherwise fill .
        /// </summary>
        internal static string Must_Be_Blank_Otherwise_Fill {
            get {
                return ResourceManager.GetString("Must_Be_Blank_Otherwise_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be either 98 or 99..
        /// </summary>
        internal static string Must_Be_Either_98Or99 {
            get {
                return ResourceManager.GetString("Must_Be_Either_98Or99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be either 0 or 1..
        /// </summary>
        internal static string Must_Be_Either_Zero_Or_One {
            get {
                return ResourceManager.GetString("Must_Be_Either_Zero_Or_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be equal or grater than the sum Of .
        /// </summary>
        internal static string Must_Be_EqualOr_GraterThan_TheSum_Of {
            get {
                return ResourceManager.GetString("Must_Be_EqualOr_GraterThan_TheSum_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be numerical..
        /// </summary>
        internal static string Must_Be_Numerical {
            get {
                return ResourceManager.GetString("Must_Be_Numerical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must be upper case..
        /// </summary>
        internal static string Must_Be_UpperCase {
            get {
                return ResourceManager.GetString("Must_Be_UpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be zero or equal to or greater than the annual Household minimum for the tax year being reported. If Empoyment code is H..
        /// </summary>
        internal static string Must_Be_Zero_OrEqual_To_OrGreater_ToHousHold_For_Year_If_Code_H {
            get {
                return ResourceManager.GetString("Must_Be_Zero_OrEqual_To_OrGreater_ToHousHold_For_Year_If_Code_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must enter blanks in both fields Orignal and Correct if no corrections are being reported to this data..
        /// </summary>
        internal static string Must_Enter_Blanks_IfNo_Corrections {
            get {
                return ResourceManager.GetString("Must_Enter_Blanks_IfNo_Corrections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not exceed social security maxtaxed earnings..
        /// </summary>
        internal static string Must_Not_Exceed_SocialSecurity_MaxTaxedEarnings {
            get {
                return ResourceManager.GetString("Must_Not_Exceed_SocialSecurity_MaxTaxedEarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not start with .
        /// </summary>
        internal static string Must_Not_Start_With {
            get {
                return ResourceManager.GetString("Must_Not_Start_With", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not correct money data..
        /// </summary>
        internal static string Not_Correct_MoneyData {
            get {
                return ResourceManager.GetString("Not_Correct_MoneyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Employee records is not correct..
        /// </summary>
        internal static string NumberOf_Employee_Records_IsNot_Correct {
            get {
                return ResourceManager.GetString("NumberOf_Employee_Records_IsNot_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Employee-Optional records is not correct..
        /// </summary>
        internal static string NumberOf_EmployeeOptional_Records_IsNotCorrect {
            get {
                return ResourceManager.GetString("NumberOf_EmployeeOptional_Records_IsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position added more than once in BlankList..
        /// </summary>
        internal static string Position_AddedMore_ThanOnce_InBlankList {
            get {
                return ResourceManager.GetString("Position_AddedMore_ThanOnce_InBlankList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postion and Length is not correct..
        /// </summary>
        internal static string Postion_And_Length_IsNot_Correct {
            get {
                return ResourceManager.GetString("Postion_And_Length_IsNot_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postion is not set..
        /// </summary>
        internal static string Postion_Is_Not_Set {
            get {
                return ResourceManager.GetString("Postion_Is_Not_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparer code is not valid..
        /// </summary>
        internal static string PreparerCode_IsNot_Valid {
            get {
                return ResourceManager.GetString("PreparerCode_IsNot_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to records should not exceed .
        /// </summary>
        internal static string Records_Should_Not_Exceed {
            get {
                return ResourceManager.GetString("Records_Should_Not_Exceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove .
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared with same position.
        /// </summary>
        internal static string Shared_WithSame_Position {
            get {
                return ResourceManager.GetString("Shared_WithSame_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateCode is not valid..
        /// </summary>
        internal static string StateCode_IsNot_Valid {
            get {
                return ResourceManager.GetString("StateCode_IsNot_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax year i s not supported..
        /// </summary>
        internal static string TaxYear_IsNot_Supported {
            get {
                return ResourceManager.GetString("TaxYear_IsNot_Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function only used for .
        /// </summary>
        internal static string This_Function_Only_Use_For {
            get {
                return ResourceManager.GetString("This_Function_Only_Use_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total is not correct..
        /// </summary>
        internal static string Total_Is_Not_Correct {
            get {
                return ResourceManager.GetString("Total_Is_Not_Correct", resourceCulture);
            }
        }
    }
}
